### ISSUE TITLE
udid and firmware compatibility identifier generators?

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac-ts#15]
They should probably live here rather than on the HF2 (UF2?) website, right @mmoskal @pelikhan ?

**Comment by pelikhan** [comment]
We can clone them here as we build the side

**Comment by mmoskal** [comment]
Right. BTW it's just a random number right now.

**Comment by pelikhan** [comment]
Where is that generated I will move it to jacdac-ts

**Comment by mmoskal** [comment]
Spec tool can generate service identifiers. It will also complain if they don't look random.

**Comment by pelikhan** [comment]
Integrated in docs.
