### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac-ts#16]
Each specification needs to be version IMO. Do past specifications need stored somewhere or do we just maintain the current version?

**Comment by pelikhan** [comment]
We should version the spec in text IMO.

**Comment by pelikhan** [comment]
We have a version number in package.json which is in sync with github releases so we could use that. There is no plan to support rendering multiple versions though. I think the text should have notes and callouts if changes occured in the spec.
