### ISSUE TITLE
replace JACDAC DOM by JDOM

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac-ts#84]
JACDAC DOM  (DOM/dom for short) doesn't make sense (it's not a document object model).  Prefer JACDAC OM (JDOM/jdom for short) as it reads "JACDAC Object Model". Replacements (in doc and code):

- DOM -> JDOM
- JACDAC DOM -> JACDAC OM
- /dom/ -> /jdom/ (directory)
- jacdoc-dom -> jacdac-om

**Comment by pelikhan** [comment]
I would like to use "jdom" everywhere just for the sake of search.

* jacdoc-dom -> jacdac-jdom
