### ISSUE TITLE
add third level to tree view of left-hand side menu

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac-ts#95]
It would be good to have a tree view on the left-hand side that could support more than two levels. For now, a third level would be useful.

**Comment by jamesadevine** [comment]
Do I need to file a separate issue about indentation? Or does this cover it?

**Comment by pelikhan** [comment]
File a separate one.

**Comment by pelikhan** [comment]
Do you already have that?

**Comment by tballmsft** [comment]
all good!
